---
title: "RME Correlation Analysis"
author: "Frédéric"
date: "01/06/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse) # general utility & workflow functions
library(tidytext) # tidy implimentation of NLP methods
library(readxl)
knitr::opts_knit$set(root.dir = "C:/Usersfjytomas/OneDrive - Tilburg University/Documents/INLG-Eval-Public Data-20220503T073540Z-001/ReProGen/Table 8/SpearmanNoMode")
```

```{r}
read_ratings <- read_excel("correlation_ranks_RME.xlsx", sheet = "read_rank_all")
cohe_ratings <- read_excel("correlation_ranks_RME.xlsx", sheet = "cohe_rank_all")
```

#readability
```{r}
res <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_rank_all, 
                    method = "spearman")
res
res2 <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_rank_all,  method="kendall")
res2
```

```{r}
res <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_rank_above, 
                    method = "spearman")
res
res2 <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_rank_above,  method="kendall")
res2
```

```{r}
res <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_rank_below, 
                    method = "spearman")
res
res2 <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_rank_below,  method="kendall")
res2
```

```{r}
res <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_q1yes, 
                    method = "spearman")
res
res2 <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_q1yes,  method="kendall")
res2
```
```{r}
res <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_q1no, 
                    method = "spearman")
res
res2 <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_q1no,  method="kendall")
res2
```
```{r}
res <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_q2yes, 
                    method = "spearman")
res
res2 <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_q2yes,  method="kendall")
res2
```
```{r}
res <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_q2no, 
                    method = "spearman")
res
res2 <- cor.test(read_ratings$`Ground Truth`, read_ratings$read_q2no,  method="kendall")
res2
```

#Coherence

```{r}
res <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_rank_all, 
                method = "spearman")
res
res2 <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_rank_all,  method="kendall")
res2
```

```{r}
res <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_rank_above, 
                method = "spearman")
res
res2 <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_rank_above,  method="kendall")
res2
```

```{r}
res <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_rank_below, 
                method = "spearman")
res
res2 <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_rank_below,  method="kendall")
res2
```

```{r}
res <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_q1yes, 
                method = "spearman")
res
res2 <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_q1yes,  method="kendall")
res2
```
```{r}
res <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_q1no, 
                method = "spearman")
res
res2 <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_q1no,  method="kendall")
res2
```
```{r}
res <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_q2yes, 
                method = "spearman")
res
res2 <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_q2yes,  method="kendall")
res2
```
```{r}
res <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_q2no, 
                method = "spearman")
res
res2 <- cor.test(cohe_ratings$`Ground Truth`, cohe_ratings$cohe_q2no,  method="kendall")
res2
```